### PR TITLE
Fix API docs typo

### PR DESCRIPTION
**Pull request by Turbo87**

### CODE REVIEW

**Comment by damiencaselli** [comment]
This PR is a proof people actually read the docs.

**Comment by Turbo87** [comment]
@damiencaselli weeeeeelll.... actually I read the code 😆

**Comment by damiencaselli** [comment]
You just ruined a kid's dream.

**Comment by Turbo87** [comment]
@damiencaselli I have to admit that I didn't know that there were published API docs. I just tried the link (https://damiencaselli.github.io/ember-cli-sentry/), but it resulted in a DNS error for `dcsl.li`. 🤔

**Comment by damiencaselli** [comment]
Well that was actually an issue, thanks for the heads up on this 😄

**Pull request merged**
