### PR TITLE
Install and import raven-js dependency

### PR DESCRIPTION
**Pull request by achambers**
Fixes 2) and 3) in #35

### CODE REVIEW

**Comment by damiencaselli** [comment]
Thanks for the nice addition!

**Comment by achambers** [comment]
@damiencaselli No probs. Any chance you might know when you'll be able to cut a release including this change?

**Comment by damiencaselli** [comment]
I was thinking about doing it right now, but I got some errors while running `ember test`.

**Comment by damiencaselli** [comment]
@achambers this is now included in the 2.1.0 release.

Thanks very much!

**Comment by achambers** [comment]
Thanks @damiencaselli

**Comment by damiencaselli** [comment]
I think this is achievable by adding an option to the `ember-cli-build.js` file, but I have little to no time to try this.

@achambers @devinus do you think you could subit a PR with a fix?

**Pull request merged**
