### PR TITLE
Stay quiet unless debugging enabled.

### PR DESCRIPTION
**Pull request by kkumler**
That logger line was annoying some folks here, so would be nice to only emit it when debugging is enabled.

### CODE REVIEW

**Comment by damiencaselli** [comment]
Thanks for PR 👍 

Can you just tell me what the annoyance was? Beside a single log line, I can't think of any case where it breaks.

**Comment by kkumler** [comment]
@damiencaselli The log statement gets spit out during some integration tests. It ends up being the only console log line, which causes a much larger chunk of test output to be filtered out, so not emitting it would be a nicety.

**Comment by damiencaselli** [comment]
I released this in `2.3.3` tag, just in case this was blocking.

**Comment by kkumler** [comment]
@damiencaselli Thanks!

**Pull request merged**
