### PR TITLE
use raven-js from npm

### PR DESCRIPTION
**Pull request by tchak**
This is a split of #66. Only `npm` part is included. But some preparation are made to ease fastboot support in the future like remove globals usage.

### CODE REVIEW

**Comment by damiencaselli** [comment]
LGTM.

@tchak do you think we can merge this PR and release the 3.0.0?
PR #79 should be closed after we merge this one.

**Comment by mazondo** [comment]
We're using this in production without issue, fwiw 👍

**Comment by marcemira** [comment]
Same, working greate here. @damiencaselli please merge and release a new version with this!! :+1: :pray:

**Comment by damiencaselli** [comment]
This is released in the `3.0.0-beta` on npm.
@marcemira @mazondo can you please let me know if you encounter any issue?

**Comment by kmiyashiro** [comment]
@damiencaselli Does this mean 3.0 will no longer have an option to include raven from a CDN and we will be pinned to the ember-cli version?

**Comment by damiencaselli** [comment]
@kmiyashiro yes indeed.

From my perspective, this option was an artifact of the first releases, which is why it got removed. If there this option is still being used, I think this can be easily put back in if people need the CDN option. See this specific diff https://github.com/damiencaselli/ember-cli-sentry/pull/81/commits/505154c0fe51d6c1d683ff42be704856a20a6df2#diff-168726dbe96b3ce427e7fedce31bb0bc

However, may be adding the `raven-js` dependency to this addon is not suitable to some users.

If the plugin had the CDN option and it let the Ember application decide which `raven-js` version it need, would it be a better workaround?

**Pull request merged**
