### PR TITLE
use raven from npm and add fastboot support

### PR DESCRIPTION
**Pull request by tchak**
I know this is a pretty big PR. I am ready to iterate if you have some concerns.

- I removed `bower` as with next version of `ember-cli` it's usage will be deprecated anyway.
- Fastboot support make usage of `raven-node`.
- The `Object.defineProperty` "hack" is there because of async loading from `cdn`. Not sure what to do about it. I am actually curious, why this option is even there? Initializer depends on the raven presence, so it's not like that app can load without raven and initialise it later.

### CODE REVIEW

**Comment by arschmitz** [comment]
These seems like the correct approach rather then #63

**Comment by arschmitz** [comment]
@tchak i tried out this PR today and it seems to be working fine from the browser, but i'm not seeing any logs from fastboot despite seeing errors in my server log

**Comment by arschmitz** [comment]
@tchak had missed this before but saw in logs 
`raven@1.1.1 alert: failed to send exception to sentry: HTTP Error (401): Invalid api key` so it looks like the DSN must not be making it to `raven-node` did look into it yet. Its working fine in the browser so i know my config and dsn are good

**Comment by tchak** [comment]
I figured it out. In sentry there is secret DSN and a public DSN. Javascript integration uses public DSN where node uses secret DSN. We will have to take this in to account in the config while being careful to not expose secret DSN to the web page.

**Comment by brunowego** [comment]
I swear I was going create a pull request to do that. Thanks @tchak 👍

**Comment by OpakAlex** [comment]
can you fix conflicts?

**Comment by leizhao4** [comment]
Bump. Would be great to have a new 📦  instead of using a fork.

**Comment by tchak** [comment]
I talked with @LewisJEllis about adding support for public API key to `raven-node`. It will make this addon much simpler as we will not have to provide both public and private keys in the configuration (and so do all the additional work to make sure private key is not leaked to the browser).

`raven-node` issue https://github.com/getsentry/raven-node/issues/303

**Comment by mirague** [comment]
This relates to #77

**Comment by mirague** [comment]
+1 would love to see this merged.

**Comment by leizhao4** [comment]
Is it possible to release just the npm part without fastboot support (if it takes time)?

**Comment by tchak** [comment]
@leizhao4 it sims that discussion with sentry team getting more complicated then what I expected. I will try to work on an alternative solution. Release just the npm part in the mean time sounds good to me.

**Comment by damiencaselli** [comment]
LGTM

**Comment by damiencaselli** [comment]
To all interested in this PR, there is an interesting discussion initiated by @tchak in this issue: getsentry/raven-node#303

**Comment by tchak** [comment]
I opened #81 with just `npm` part. We also have #79. Both use different strategies. Mine is to remove `cdn` option and make `npm` default and no optout. I am also not a huge fan of adding dependencies to `package.json` file from addons as it makes upgrades harder. I suggested drop `bower` and `cdn` and release `3.0.0`.

**Comment by Turbo87** [comment]
this is obsolete now that #81 was merged. @tchak can you open a separate PR for the fastboot support?

**Pull request closed without merging**
